SELECT 
A.BUKRS AS COMPANY_CODE,
A1.BUTXT AS COMPANY_NAME,
MAND1.DDTEXT AS COMPANY_NAME_MAND,
B.ESTNR AS ESTATE_CODE,
A.PRFNR AS ESTATE_NAME,
MAND2.DDTEXT AS ESTATE_NAME_MAND,
REG.RGNNR AS REGION_CODE,
REG.NAME1 AS REGION_NAME,
MAND3.DDTEXT AS REGION_NAME_MAND,
C.DIVNR AS DIVISION_CODE,
C.NAME1 AS DIVISION_NAME,
D.BLOCK AS BLOCK_CODE,
D.BNAME AS BLOCK_NAME,
D.SEEDO AS BIBIT,
D.YPLAN AS TAHUN_TANAM,
I.BUDAT AS TANGGAL_LOOSE,
I.BUDAT_BCC AS CATATAN,
'BERONDOLAN' AS MEASURE_NAME,
I.BERONDOLAN AS MEASURE_VALUE,
I.TDN AS JANJANG,
I.NWEIG AS FFB_TONAGE,
I.OPH AS MEASURE_DESC
FROM STG_ZPAY_PROFILE A
LEFT JOIN STG_T001 A1
ON A.BUKRS = A1.BUKRS
LEFT JOIN STG_ZEST_ESTATE B
ON A.BUKRS = B.BUKRS
AND RIGHT(TRIM(A.WERKS),2) = B.ESTNR
LEFT JOIN STG_ZEST_REGION REG
ON B.RGNNR = REG.RGNNR
LEFT JOIN STG_DD07T MAND1
on A.BUKRS = MAND1.DOMVALUE_L
and TRIM(MAND1.DOMNAME) = 'ZDMCOMPANY'
LEFT JOIN STG_DD07T MAND2
on B.WERKS = MAND2.DOMVALUE_L
and TRIM(MAND2.DOMNAME) = 'ZDMESTATE'
left join STG_DD07T MAND3
on REG.RGNNR = MAND3.DOMVALUE_L
and TRIM(MAND3.DOMNAME) = 'ZDMREGION'
LEFT JOIN STG_ZEST_DIVISION C
ON B.ESTNR = C.ESTNR
AND A.BUKRS = C.BUKRS
AND C.KDATE = '9999-12-31'
LEFT JOIN STG_ZEST_BLOCK D
ON D.BUKRS = A.BUKRS
AND B.ESTNR = D.ESTNR
AND C.DIVNR = D.DIVNR
INNER JOIN (SELECT A.BUKRS, A.ESTNR, A.DIVNR, A.BLOCK, A.OPH, A.BUDAT, BERONDOLAN, TDN, NWEIG, B.BUDAT AS BUDAT_BCC
FROM (SELECT BUKRS, ESTNR, DIVNR, BLOCK, OPH, BUDAT, SUM(LOOSE) BERONDOLAN, SUM(TDN) TDN
FROM STG_ZEST_NOSPB
GROUP BY BUKRS,ESTNR, DIVNR, BLOCK, OPH, BUDAT) A
LEFT JOIN STG_ZPAY_BCC B
ON A.BUKRS = B.BUKRS
AND A.ESTNR = B.ESTNR
AND A.DIVNR = B.DIVNR
AND A.BLOCK = B.BLOCK
AND A.OPH = B.OPH) I
ON A.BUKRS = I.BUKRS
AND B.ESTNR = I.ESTNR
AND C.DIVNR = I.DIVNR
AND D.BLOCK = I.BLOCK
WHERE D.KDATE >= I.BUDAT